// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace TimeTrackingAPI.Models
{
    public partial class DepartmentEntity
    {
        public DepartmentEntity()
        {
            Employees = new HashSet<EmployeeEntity>();
        }
        [Key]
        public int DepartmentID { get; set; }
        public string DepartmentName { get; set; }

        public virtual ICollection<EmployeeEntity> Employees { get; set; }
    }
}