// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace TimeTrackingAPI.Models
{
    public partial class EmployeeEntity
    {
        public EmployeeEntity()
        {
            TimeRecords = new HashSet<TimeRecordEntity>();
        }
        [Key]
        public int EmployeeID { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public int DepartmentID { get; set; }

        public virtual DepartmentEntity Department { get; set; }
        public virtual ICollection<TimeRecordEntity> TimeRecords { get; set; }
    }
}