// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TimeTrackingAPI.Models
{
    public partial class Employee
    {
        public Employee()
        {
            TimeRecords = new HashSet<TimeRecord>();
        }

        public int EmployeeId { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public int DepartmentId { get; set; }

        public virtual Department Department { get; set; }
        public virtual ICollection<TimeRecord> TimeRecords { get; set; }
    }
}