// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace TimeTrackingAPI.Models
{
    public partial class ProjectEntity
    {
        public ProjectEntity()
        {
            Tasks = new HashSet<TaskEntity>();
        }
        [Key]   
        public int ProjectId { get; set; }
        public string ProjectName { get; set; }
        public int ProjectTypeId { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime EndDate { get; set; }
        public decimal Budget { get; set; }

        public virtual ProjectTypeEntity ProjectType { get; set; }
        public virtual ICollection<TaskEntity> Tasks { get; set; }
    }
}