// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace TimeTrackingAPI.Models
{
    public partial class ProjectTypeEntity
    {
        public ProjectTypeEntity()
        {
            Projects = new HashSet<ProjectEntity>();
        }
        [Key]
        public int ProjectTypeId { get; set; }
        public string TypeName { get; set; }

        public virtual ICollection<ProjectEntity> Projects { get; set; }
    }
}