// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TimeTrackingAPI.Models
{
    public partial class ProjectType
    {
        public ProjectType()
        {
            Projects = new HashSet<Project>();
        }

        public int ProjectTypeId { get; set; }
        public string TypeName { get; set; }

        public virtual ICollection<Project> Projects { get; set; }
    }
}