// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TimeTrackingAPI.Models
{
    public partial class Tag
    {
        public Tag()
        {
            Tasks = new HashSet<Task>();
        }

        public int TagId { get; set; }
        public string TagName { get; set; }

        public virtual ICollection<Task> Tasks { get; set; }
    }
}