// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace TimeTrackingAPI.Models
{
    public partial class TagEntity
    {
        public TagEntity()
        {
            TaskTags = new HashSet<TaskTagEntity>();
        }
        [Key]
        public int TagId { get; set; }
        public string TagName { get; set; }

        public ICollection<TaskTagEntity> TaskTags { get; set; }

    }
}