// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TimeTrackingAPI.Models
{
    public partial class Task
    {
        public Task()
        {
            TimeRecords = new HashSet<TimeRecord>();
            Tags = new HashSet<Tag>();
        }

        public int TaskId { get; set; }
        public string TaskName { get; set; }
        public string Description { get; set; }
        public int ProjectId { get; set; }
        public string Status { get; set; }
        public int Priority { get; set; }

        public virtual Project Project { get; set; }
        public virtual ICollection<TimeRecord> TimeRecords { get; set; }

        public virtual ICollection<Tag> Tags { get; set; }
    }
}