// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace TimeTrackingAPI.Models
{
    public partial class TimeRecordEntity
    {
        [Key]
        public int TimeRecordId { get; set; }
        public int EmployeeId { get; set; }
        public int TaskId { get; set; }
        public DateTime StartTime { get; set; }
        public DateTime EndTime { get; set; }
        public decimal HoursSpent { get; set; }

        public virtual EmployeeEntity Employee { get; set; }
        public virtual TaskEntity Task { get; set; }
    }
}